### ISSUE TITLE
`jenkins.model.Jenkins` default value breaks empty context form round trip

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/extension-filter-plugin#49]
https://github.com/jenkinsci/extension-filter-plugin/blob/33202c8708d46c2e57466ecbb4a2d7e10620363c/src/main/java/org/jenkinsci/plugins/Exclusion.java#L23 and https://github.com/jenkinsci/extension-filter-plugin/blob/33202c8708d46c2e57466ecbb4a2d7e10620363c/src/main/java/org/jenkinsci/plugins/ConfigurableExtensionFilter.java#L92 indicate it should be possible to have a `null` context.

https://github.com/jenkinsci/extension-filter-plugin/blob/33202c8708d46c2e57466ecbb4a2d7e10620363c/src/main/resources/org/jenkinsci/plugins/ConfigurableExtensionFilter/global.jelly#L12 breaks round-trip behavior, as it will replace a `null` value with `jenkins.model.Jenkins` on subsequent form submissions.

`JenkinsRule#configRoundtrip` can help write a test.

**Comment by jonesbusy** [comment]
Thanks I will try to take a look at it unless someone pick it before.

Plugin need other refresh (example https://github.com/jenkinsci/extension-filter-plugin/issues/54)
