### ISSUE TITLE
Missing test coverage

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/extension-filter-plugin#67]
### What feature do you want to see added?

This plugin is missing test coverage like integration tests to ensure Extension and Descriptor are actually deactivated

**Comment by jglick** [comment]
Should also have a CasC test.

**Comment by jglick** [comment]
And a `configRoundtrip` test. Check the archetype for global config for ideas.

**Comment by jonesbusy** [comment]
Fixed (JcasC, roundtrip and unit test) over the past months
