### ISSUE TITLE
Nonstandard config GUI

### ISSUE THREAD

**Issue by jglick** [jenkinsci/extension-filter-plugin#91]
https://github.com/jenkinsci/extension-filter-plugin/blob/b808bd41273d1dce0c37f67be1b8a628f3766197/src/main/resources/org/jenkinsci/plugins/ConfigurableExtensionFilter/global.jelly#L6-L20 should be replaced by a standard `f:repeatableProperty`, giving a `config.jelly` to `Exclusion`.

**Comment by jonesbusy** [comment]
Thanks for your report, I didn't pay attention to it when adopting the plugin

I've submitted a PR https://github.com/jenkinsci/extension-filter-plugin/pull/108 to use the `repeatableProperty` and `config.jelly` for `Exclusion`
